### PR TITLE
fix typo in vulnrichment_big.dot

### PR DESCRIPTION
**Pull request by jrheling**
#  #

## 🗣 Description ##

Fix typo.

## 💭 Motivation and context ##

Improved readability.

## 🧪 Testing ##

N/A

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by amanion-cisa — APPROVED** [review]
LGTM thanks.

**Comment by todb-cisa** [comment]
@amanion-cisa do you want to regenerate your chart from this then land this when you're ready? LGTM too.

**Comment by todb-cisa** [comment]
poke @amanion-cisa

**Review by amanion-cisa — APPROVED** [review]
bumped date, will update svg file

**Pull request merged**
